### ISSUE TITLE
Logistics before diving into real development

### ISSUE THREAD

**Issue by gabrielwry** [mediconnect/backend#1]
## Database
- MySQL?
- Configuration 
    - Isolation Level? current = read committed
    - time zone support? current = not set up yet
    - table engine?  current = INNODB
    - name, password, user, etc
    - etc.

**Comment by Arnoldosmium** [comment]
Database: Suggest PostgreSQL, MySQL also works i believe

Definition of "Isolation level"? The isolation of database from any users (customers + admins) accessible to the platform?

Timezone: use UTC (GMT) timestamp. Frontend package can decipher the timestamp correctly.

Not sure what table engine is. (Django related?)

Suggest 1 admin user, 1 api user (assuming using psql)
