### ISSUE TITLE
User module

### ISSUE THREAD

**Issue by gabrielwry** [mediconnect/backend#2]
Shouldn't we start a user module and put user-related serializer/views there to avoid redundant code, and be consistent through customer/supervisor/translator apis.

**Comment by jiashenC** [comment]
For now the redundant one could be UserLoginSerializer. Maybe move that to separate User module. But the User module should not provide any API service, just store the serializers.

**Comment by gabrielwry** [comment]
Maybe also UserRegistrationSerializer?

**Comment by jiashenC** [comment]
Are you going to provide registration service to translator and supervisor?

**Comment by gabrielwry** [comment]
yes, but only authorized supervisor can register/create supervisor/translator
